npad: 5
res: 10
ntrain: 5000
modes: 300
val_data_percent: 1
domain_padding: 0.20

train_data: data/data_more_processing/axis_magnitude_train_data.pkl
test_data: data/data_more_processing/axis_magnitude_test_data.pkl
periment_name: 'experiment-1'

d_co_domain: 150
lr: 1.0e-4 
epochs: 5000
Î»_grad: 10.0
hm_weight: 0.15
fc_weight: 0.15
gt_weight: 10.0
n_critic: 1
batch_size: 32

alpha: 3 
tau: 23 
codim: 1
device: 'cuda:0' 

logging:
    G_move_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Gen/move/
    G_orient_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Gen/orient/
    G_betas_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Gen/betas/
    G_hands_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Gen/hands/
    G_legs_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Gen/legs/
    G_torso_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Gen/torso/
    

    G_move_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Gen/move/
    G_orient_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Gen/orient/
    G_betas_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Gen/betas/
    G_hands_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Gen/hands/
    G_legs_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Gen/legs/
    G_torso_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Gen/torso/

    G_move_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Gen/move/
    G_orient_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Gen/orient/
    G_betas_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Gen/betas/
    G_hands_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Gen/hands/
    G_legs_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Gen/legs/
    G_torso_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Gen/torso/


    D_move_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Dis/move/
    D_orient_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Dis/orient/
    D_betas_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Dis/betas/
    D_hands_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Dis/hands/
    D_legs_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Dis/legs/
    D_torso_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Models/Dis/torso/

    D_move_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Dis/move/
    D_orient_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Dis/orient/
    D_betas_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Dis/betas/
    D_hands_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Dis/hands/
    D_legs_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Dis/legs/
    D_torso_optimizer_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Optims/Dis/torso/

    D_move_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Dis/move/
    D_orient_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Dis/orient/
    D_betas_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Dis/betas/
    D_hands_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Dis/hands/
    D_legs_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Dis/legs/
    D_torso_scheduler_save_path: /home/arunreddy/ML/Cloud-Storage/weights_100/Schedulers/Dis/torso/

    

    plots: /home/arunreddy/ML/Cloud-Storage/plots_100/

    vis_test_results_path: /home/arunreddy/ML/Cloud-Storage/test_results_100/
    vis_train_results_path: /home/arunreddy/ML/Cloud-Storage/train_results_100/
    log_loss_path: /home/arunreddy/ML/Cloud-Storage/loss_log_100.txt

    final_result_path: /home/arunreddy/ML/Cloud-Storage/final_results_100/


resume: False
resume_epoch: 0

move_dim_info: 3
orient_dim_info: 3
betas_dim_info: 16
hands_dim_info: 152
legs_dim_info: 32
torso_dim_info: 36

res: 300
n_feat: 5


