npad: 5
res: 10
ntrain: 5000
modes: 300
val_data_percent: 1

train_data: data/data_more_processing/axis_magnitude_train_data_150.pkl
test_data: data/data_more_processing/axis_magnitude_test_data_150.pkl

d_co_domain: 150
lr: 1.0e-4 
epochs: 500000
Î»_grad: 10.0
hm_weight: 0.15
fc_weight: 0.15
gt_weight: 10.0
n_critic: 1
batch_size: 1
domain_padding: 5

alpha: 3 
tau: 23 
codim: 120 
device: 'cuda:0' 

logging:
    G_move_save_path: /scratch/gilbreth/anugu/weights_15/Models/Gen/move/
    G_orient_save_path: /scratch/gilbreth/anugu/weights_15/Models/Gen/orient/
    G_betas_save_path: /scratch/gilbreth/anugu/weights_15/Models/Gen/betas/
    G_hands_save_path: /scratch/gilbreth/anugu/weights_15/Models/Gen/hands/
    G_legs_save_path: /scratch/gilbreth/anugu/weights_15/Models/Gen/legs/
    G_torso_save_path: /scratch/gilbreth/anugu/weights_15/Models/Gen/torso/
    

    G_move_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Gen/move/
    G_orient_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Gen/orient/
    G_betas_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Gen/betas/
    G_hands_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Gen/hands/
    G_legs_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Gen/legs/
    G_torso_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Gen/torso/

    G_move_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Gen/move/
    G_orient_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Gen/orient/
    G_betas_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Gen/betas/
    G_hands_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Gen/hands/
    G_legs_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Gen/legs/
    G_torso_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Gen/torso/


    D_move_save_path: /scratch/gilbreth/anugu/weights_15/Models/Dis/move/
    D_orient_save_path: /scratch/gilbreth/anugu/weights_15/Models/Dis/orient/
    D_betas_save_path: /scratch/gilbreth/anugu/weights_15/Models/Dis/betas/
    D_hands_save_path: /scratch/gilbreth/anugu/weights_15/Models/Dis/hands/
    D_legs_save_path: /scratch/gilbreth/anugu/weights_15/Models/Dis/legs/
    D_torso_save_path: /scratch/gilbreth/anugu/weights_15/Models/Dis/torso/

    D_move_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Dis/move/
    D_orient_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Dis/orient/
    D_betas_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Dis/betas/
    D_hands_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Dis/hands/
    D_legs_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Dis/legs/
    D_torso_optimizer_save_path: /scratch/gilbreth/anugu/weights_15/Optims/Dis/torso/

    D_move_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Dis/move/
    D_orient_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Dis/orient/
    D_betas_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Dis/betas/
    D_hands_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Dis/hands/
    D_legs_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Dis/legs/
    D_torso_scheduler_save_path: /scratch/gilbreth/anugu/weights_15/Schedulers/Dis/torso/

    

    plots: /scratch/gilbreth/anugu/plots_15/

    vis_test_results_path: /scratch/gilbreth/anugu/test_results_15/
    vis_train_results_path: /scratch/gilbreth/anugu/train_results_15/
    log_loss_path: /scratch/gilbreth/anugu/loss_log_15.txt

    final_result_path: /scratch/gilbreth/anugu/final_results_15/


resume: True
resume_epoch: 4300

move_dim_info: 3
orient_dim_info: 3
betas_dim_info: 16
hands_dim_info: 152
legs_dim_info: 32
torso_dim_info: 36

res: 150
n_feat: 5


